name: PHP Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none
        
    - name: Validate composer.json and composer.lock
      run: |
        if [ -f "composer.json" ]; then
          composer validate --strict test
        fi

    - name: Install dependencies
      run: |
        if [ -f "composer.json" ]; then
          composer install --prefer-dist --no-progress
        fi

    - name: Run test suite
      run: |
        if [ -f "phpunit.xml" ]; then
          vendor/bin/phpunit
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: true
